apiVersion: skaffold/v2beta1
kind: Config
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: eduhub-online
    timeout: 600s 
  artifacts:
    - image: us.grc.io/eduhub-online/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/course
      context: courses
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/category
      context: category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/profile
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/purchase
      context: purchase
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/message
      context: message
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.grc.io/eduhub-online/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*