apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: pkansif/eduhub-auth:latest
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-course:latest
      context: courses
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-category:latest
      context: category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-profile:latest
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-purchase:latest
      context: purchase
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-message:latest
      context: message
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: pkansif/eduhub-client:latest
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.tsx"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*