apiVersion: skaffold/v2beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: eduhub/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: eduhub/category
      context: category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*