apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: auth-srv
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /metrics
    interval: 15s