apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: '16m'
spec:
  ingressClassName: nginx
  rules:
    - host: ansifpk.dev
      http:
        paths:
          - path: /auth/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /category/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: category-srv
                port:
                  number: 3001
          - path: /course/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: course-srv
                port:
                  number: 3002
          - path: /purchase/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: purchase-srv
                port:
                  number: 3003
          - path: /profile/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: profile-srv
                port:
                  number: 3004
          - path: /message/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: message-srv
                port:
                  number: 3006
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 5173
          

         
          