apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: "50mb"
spec:
  rules:
    - host: eduhub.dev
      http:
        paths:
          - path: /auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /category/?(.*)
            pathType: Prefix
            backend:
              service:
                name: category-srv
                port:
                  number: 3001
          - path: /course/?(.*)
            pathType: Prefix
            backend:
              service:
                name: course-srv
                port:
                  number: 3002
          - path: /purchase/?(.*)
            pathType: Prefix
            backend:
              service:
                name: purchase-srv
                port:
                  number: 3003
          - path: /profile/?(.*)
            pathType: Prefix
            backend:
              service:
                name: profile-srv
                port:
                  number: 3004
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 5173
          

         
          