export enum Topics{
    userCreated = "user-created",
    profileCreated = "profile-created",
    profileUpdated = "profile-updated",
    userBlcoked = "user-blocked",
    instructorAproved = "instructor-aproved",
    courseCreated = "course-created",
    courseUpdated = "course-updated",
    courseListed = "course-listed",
    orderCreated = "order-created",
    videosUploaded = "videos-uploaded",
    couponUsed = "coupon-used",
    emailChanged= "email-changed",
    userUpdated = "user-updated",
}